USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DW_Orders;
CREATE SCHEMA IF NOT EXISTS DW_Orders.RAW;

CREATE DATABASE IF NOT EXISTS DW_Manage;
CREATE SCHEMA IF NOT EXISTS DW_Manage.file_formats;
CREATE SCHEMA IF NOT EXISTS DW_Manage.external_stages;
CREATE SCHEMA IF NOT EXISTS DW_Manage.file_formats;


CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
WAREHOUSE_SIZE=XSMALL
MAX_CLUSTER_COUNT=1
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

CREATE USER IF NOT EXISTS dbt
    PASSWORD='dbtPassword123'
    LOGIN_NAME='dbt'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_ROLE='transform'
    DEFAULT_NAMESPACE='DW_Orders.RAW' 
    COMMENT='DBT user used for data transformation';


CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;
GRANT ROLE transform to USER dbt;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE transform;
GRANT ALL ON DATABASE DW_Orders to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE DW_Orders to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DW_Orders to ROLE transform;

GRANT ALL ON ALL TABLES IN SCHEMA DW_Orders.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA DW_Orders.RAW to ROLE transform;
