name: 'dbt_orders'
version: '1.0.0'
config-version: 2

profile: 'dbt_orders'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  dbt_orders:
    +transient: true
    stg:
      +materialized: view
    dim:
      +materialized: table
    fact:
      # +transient: false
      +materialized: incremental

vars:
  "dbt_date:time_zone": "Europe/Warsaw" # dbt_date package configuration
  dim_date_start_date: "2018-01-01"
  dim_date_end_date: "2023-01-01"